version: 0.0
os: linux

files:
  - source: target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/cicd/
    
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
#   BeforeInstall:
#     - location: install_dependencies.sh
#       timeout: 300
#       runas: ec2-user
#     - location: create_or_update_service.sh
#       timeout: 300
#       runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
